#!/bin/bash

while getopts ":t:s:b:p:h:k:d:" opt; do
  case $opt in
    t)
      abs_top_srcdir="$(realpath ${OPTARG%/})"
      ;;
    s)
      abs_srcdir="$(realpath ${OPTARG%/})"
      ;;
    b)
      package_bugreport="${OPTARG}"
      ;;
    p)
      prefix="${OPTARG}"
      ;;
    h)
      host_alias="${OPTARG}"
      ;;
    k)
      kernel_version="${OPTARG}"
      ;;
    d)
      pkg_path="$(realpath ${OPTARG%/})"
      ;;
    \?)
      echo "Usage!"
      exit 0
      ;;
    :)
      printf "Option -%s requires an argument.\n\n" "${OPTARG}"
      exit 1
    ;;
  esac
done      

linux_kernel=$(basename `ls -A ${pkg_path}/linux-image-*-${kernel_version}*_armhf.deb 2> /dev/null ` 2> /dev/null)
linux_headers=$(basename `ls -A ${pkg_path}/linux-headers-*-${kernel_version}*_armhf.deb  2> /dev/null` 2> /dev/null)
linux_firmware=$(basename `ls -A ${pkg_path}/linux-firmware-image-*-${kernel_version}*_armhf.deb 2> /dev/null ` 2> /dev/null)
linux_dtbs=$(basename `ls -A ${pkg_path}/linux-dtbs-*-${kernel_version}*_armhf.deb 2> /dev/null` 2> /dev/null)

linux_kernel_pkg=$(dpkg-deb -I ${pkg_path}/${linux_kernel} | grep Package: | awk '{print $2}')
linux_headers_pkg=$(dpkg-deb -I ${pkg_path}/${linux_headers} | grep Package: | awk '{print $2}')
linux_firmware_pkg=$(dpkg-deb -I ${pkg_path}/${linux_firmware} | grep Package: | awk '{print $2}')

if [ -f ${pkg_path}/${linux_dtbs} ]; then
  linux_dtbs_pkg=$(dpkg-deb -I ${pkg_path}/${linux_dtbs} | grep Package: | awk '{print $2}')
  linux_kernel_pkg="${linux_kernel_pkg}, ${linux_dtbs_pkg}"
fi

linux_version="$(cat ${abs_srcdir}/.version)-$(cat ${abs_srcdir}/.version_build)"

echo "linux_kernel_pkg ${linux_kernel_pkg=}"
echo "linux_headers_pkg ${linux_headers_pkg}"
echo "linux_firmware_pkg ${linux_firmware_pkg}"
echo "linux_version $linux_version"

armstrap_linux_headers="${linux_headers_pkg}"
armstrap_linux_headers_name="armstrap-linux-headers-${kernel_version}"
armstrap_linux_headers_desc="armStrap ${kernel_version} Linux kernel headers\n  This package will always depend on the latest armStrap ${kernel_version} kernel headers available."

armstrap_linux_image="${linux_kernel_pkg}, ${linux_firmware_pkg}"
armstrap_linux_image_name="armstrap-linux-image-${kernel_version}"
armstrap_linux_image_desc="armStrap ${kernel_version} Linux kernel image\n  This package will always depend on the latest armStrap ${kernel_version} kernel image available."

armstrap_linux="${armstrap_linux_image_name} (= ${linux_version}), ${armstrap_linux_headers_name} (= ${linux_version})"
armstrap_linux_name="armstrap-linux-${kernel_version}"
armstrap_linux_desc="Complete armStrap ${kernel_version} Linux kernel and headers\n  This package will always depend on the latest complete armStrap ${kernel_version} Linux kernel and headers."

rm -rf ${abs_srcdir}/debian
mkdir -p ${abs_srcdir}/build/${armstrap_linux_headers_name}/usr/share/doc/${armstrap_linux_headers_name}
echo -e ${armstrap_linux_image_desc} > ${abs_srcdir}/build/${armstrap_linux_headers_name}/usr/share/doc/${armstrap_linux_headers_name}/README
${SHELL} ${abs_top_srcdir}/makedeb -n ${armstrap_linux_headers_name} -v @${abs_srcdir}/.version -B @${abs_srcdir}/.version_build -s "linux-upstream" -S "devel" -u ${package_bugreport} -b ${abs_srcdir}/build/armstrap-linux-${kernel_version} -p /usr -h ${host_alias} -d "${armstrap_linux_headers} " -l "${armstrap_linux_headers_desc}"
rm -rf ${abs_srcdir}/build

rm -rf ${abs_srcdir}/debian
mkdir -p ${abs_srcdir}/build/${armstrap_linux_image_name}/usr/share/doc/${armstrap_linux_image_name}
echo -e ${armstrap_linux_image_desc} > ${abs_srcdir}/build/${armstrap_linux_image_name}/usr/share/doc/${armstrap_linux_image_name}/README
${SHELL} ${abs_top_srcdir}/makedeb -n ${armstrap_linux_image_name} -v @${abs_srcdir}/.version -B @${abs_srcdir}/.version_build -s "linux-upstream" -S "kernel" -u ${package_bugreport} -b ${abs_srcdir}/build/armstrap-linux-${kernel_version} -p /usr -h ${host_alias} -d "${armstrap_linux_image}" -l "${armstrap_linux_image_desc}"
rm -rf ${abs_srcdir}/build

rm -rf ${abs_srcdir}/debian
mkdir -p ${abs_srcdir}/build/${armstrap_linux_name}/usr/share/doc/${armstrap_linux_name}
echo -e ${armstrap_linux_desc} > ${abs_srcdir}/build/${armstrap_linux_name}/usr/share/doc/${armstrap_linux_name}/README
${SHELL} ${abs_top_srcdir}/makedeb -n ${armstrap_linux_name} -v @${abs_srcdir}/.version -B @${abs_srcdir}/.version_build -s "linux-upstream" -S "kernel" -u ${package_bugreport} -b ${abs_srcdir}/build/armstrap-linux-${kernel_version} -p /usr -h ${host_alias} -d "${armstrap_linux}" -l "${armstrap_linux_desc}"
rm -rf ${abs_srcdir}/build
rm -rf ${abs_srcdir}/debian
